#include "gradient_combined.h"
#include "metrics.h"
#include "results_export.h"
#include <iomanip>
#include <vector>
#include <iostream>


int main() {
    MLR_gradient solver;
    
    // 1 - Load the data generated by the gradient_combined.h
    solver.dataset();
    
    // 2 - Run the Iterative Optimization 
    solver.solve();
    
    // 3 - Extract results for the comparison report 
    double final_w1 = solver.w1;
    double final_w2 = solver.w2;
    double final_b  = solver.b;
    double final_error = solver.calculate_mse();

    // 4 - Calculating the accuracy of the model (R^2)
    std::vector<double> predictions = solver.predict();
    double Rsquared = calculate_Rsquared(solver.y, predictions);

    // 5 - Output results for Task 2 Report
    std::cout << "--- GRADIENT DESCENT COMPARISON ---" << std::endl;
    std::cout << "Learned Weights: [" << final_w1 << ", " << final_w2 << "]" << std::endl;
    std::cout << "Learned Bias:    " << final_b << std::endl;
    std::cout << "Mean Squared Error: " << final_error << std::endl;
    
// 6 - Display the Final Model Equation 
// Represents the final function
std::cout << "\n--- FINAL PREDICTION MODEL ---" << std::endl;
std::cout << std::fixed << std::setprecision(4);
std::cout << "Equation: y = (" << final_w1 << ")x1 + (" 
          << final_w2 << ")x2 + (" << final_b << ")" << std::endl;

// Display the accurace as % (using R^2)
// Multiplying by 100 to convert to %
std::cout <<"Model predictability:" <<(Rsquared*100.0) << "%" << std::endl;

// 7 - Saving the results table 
MLR_export(solver.x1, solver.x2, solver.y, predictions);
    
    return 0;
}